server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # ===============================
            # Authentication Service (PUBLIC)
            # ===============================
            - id: authentication-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**


            # ===============================
            # Order Service (PROTECTED)
            # ===============================
            - id: order-service
              uri: http://localhost:8082
              predicates:
                - Path=/orders/**
              filters:
                - JwtAuthenticationFilter


            # ===============================
            # Payment Service (PROTECTED)
            # ===============================
            - id: payment-service
              uri: http://localhost:8083
              predicates:
                - Path=/payments/**
              filters:
                - JwtAuthenticationFilter


            # ===============================
            # Inventory Service (PROTECTED)
            # ===============================
            - id: inventory-service
              uri: http://localhost:8084
              predicates:
                - Path=/inventory/**
              filters:
                - JwtAuthenticationFilter

            # ===============================
            # Product Service (PROTECTED)
            # ===============================
            - id: product-service
              uri: http://localhost:8085
              predicates:
                - Path=/products/**
              filters:
                - JwtAuthenticationFilter

            # ===============================
            # Notification Service (PROTECTED)
            # ===============================
            - id: notification-service
              uri: http://localhost:8086
              predicates:
                - Path=/notifications/**
              filters:
                - JwtAuthenticationFilter



# ===============================
# JWT Configuration
# ===============================

jwt:
  secret: my-super-secret-key-for-commerce-platform


# ===============================
# Actuator Monitoring
# ===============================

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway


# ===============================
# Logging
# ===============================

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG