server:
  port: 8085

spring:
  application:
    name: product-service


aws:
  region: ap-south-1

  dynamodb:
    table:
      product: products

  s3:
    bucket:
      product: ecommerce-product-images